### ISSUE TITLE
Unable to revoke clients

### ISSUE THREAD

**Issue by ashvayakov** [IBCNServices/easy-openvpn-server#1]
Hello,

I did the command:

**easy-openvpn-server remove-client alice**

But the client alice is still able to connect with the same config

I use the version - latest/candidate: 0.1 2020-02-20 

Thanks

**Comment by morticool** [comment]
I experienced the same issue with latest Version latest/candidate: 0.1 2020-02-20

I get the following results when i do this:

```
root@server:~# easy-openvpn-server add-client Test
INFO: Public addresses according to get_public_addresses: [IPv4Address('1123.123.123.123')]
INFO: Added Test. You can copy its config using
        sudo easy-openvpn-server show-client Test > Test.ovpn
root@server:~# easy-openvpn-server remove-client Test
WARNING: Could not find client config file.
WARNING: Could not find client certificate.
WARNING: Could not find client private key.

```
And the Test user cert is still available after all.

**Comment by galgalesh** [comment]
Thanks for reporting this! This was indeed a big oversight on my part and should be fixed now. With this fixed, I released the first stable version of easy-openvpn-server!

Note: if you tried to remove clients before this update, you'll have to remove them again after the update to complete the removal.
