### ISSUE TITLE
Predefined certificates and keys?

### ISSUE THREAD

**Issue by christianhodel** [IBCNServices/easy-openvpn-server#20]
Hi, are certificates and keys predefined or generated at installation?

**Comment by merlijn-sebrechts** [comment]
* CA keys & certs are generated during install: https://github.com/IBCNServices/easy-openvpn-server/blob/master/scripts/setup.py#L60
* user keys & certs are generated during add-user: https://github.com/IBCNServices/easy-openvpn-server/blob/master/scripts/setup.py#L161

**Comment by christianhodel** [comment]
Thanks for your quick reply and the great work!
