### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by seikosantana** [IBCNServices/easy-openvpn-server#5]
It works so great so far, but i have troubles to assign a static IP to client.

Is it possible to achieve this?

**Comment by galgalesh** [comment]
Assigning a static IP tot a client is currently not possible. Can you explain a bit more why you want this feature and what you would use it for?

**Comment by seikosantana** [comment]
I use this easy-openvpn-server to connect multiple offices. It would be easier if i could assign static IP to specific computers that i don't want the IP to change.

For now i wrote a script to get the IP address from the easy-openvpn-server.status and grep the IP out, but still, if i can manage the addresses manually it would be good.

**Comment by reverland** [comment]
In some environments, there is no way to get ip public addresses automaticly.
There is indeed a need for static ip

**Comment by seikosantana** [comment]
Configurable and is fixed with Wireguard
