### ISSUE TITLE
Number of simultaneous connections

### ISSUE THREAD

**Issue by Atta-Seve** [IBCNServices/easy-openvpn-server#6]
Hello,
Using this application, how many simultaneous connections are possible for each config?

**Comment by galgalesh** [comment]
As much as your server can handle. Multiple connections per client config are allowed in the server configuration.

**Comment by Atta-Seve** [comment]
Thanks for answer!
And how can I set a limit?
For example, for each config file, only 3 devices are allowed to connect at the same time.

**Comment by galgalesh** [comment]
That is not possible with this snap. I don't think I want to add that functionality. The goal of the snap is to be as simple as possible, but this also means that the snap only supports a limited set of use-cases. For more complex scenarios it might be better to manually install and configure OpenVPN.
