### ISSUE TITLE
Losing Connection to Local Network

### ISSUE THREAD

**Issue by seikosantana** [IBCNServices/easy-openvpn-server#7]
Hi, i've set up VPN on a server with network manager, and have it connected to internet over WiFi, but i am having issues that i cannot connect to devices on local network over ethernet. Now I have my laptop and my local server connected to VPN but i cannot reach devices on ethernet conencted to the local server.

I'm not actually sure if this is an issue with the easy-openvpn-server, but some forums mentioned that it might have something to do with the vpn policy.

I've tried setting the vpn to have never-default enabled but i still get the same result. Is there anything I possibly should check into to get that working?
Thanks in advance

**Comment by galgalesh** [comment]
It's not clear from your description what you're trying to do here. Can you draw a network diagram, show which device is VPN server and which is VPN client, and show with arrows what connection doesn't work?

Also give the following info:

* What is the ipv4 network your client is on and what is the ipv4 network your server is on?
* Are you using ipv4 or ipv6?
* Are you connecting via hostname or are you typing in the ip addresses of the devices directly?

**Comment by seikosantana** [comment]
Hi, sorry it was a fault on my network configuration and i figured it out, i guess.

But maybe there is a better way to work things out? I wasn't that good in networking too, but here are some details.

What is the ipv4 network your client is on and what is the ipv4 network your server is on?
The client is on 192.168.100.28 (DHCP, local), and the server is on cloud server with public IP (95.111.x.x)

Are you using ipv4 or ipv6?
It's IPv4

Are you connecting via hostname or are you typing in the ip addresses of the devices directly?
I didn't type hostnames in, nor type in the IP address of the devices to connect to the OpenVPN server. Instead, I exported an OpenVPN configuration with sudo easy-openvpn-server show-client alice > alice.ovpn and have the client connected by importing the configuration from the  network settings GUI in Ubuntu.

![Network diagram](https://user-images.githubusercontent.com/35630407/134818790-4012ff2c-e231-481c-978b-4b87525fcf89.jpg)

**Comment by seikosantana** [comment]
Issues aren't happening with Wireguard
